### ISSUE TITLE
Issue installing @angular-cli after npm 5.3

### ISSUE THREAD

**Issue by ghost** [mhart/alpine-node#100]
Something has changed in the last couple days (likely thanks to npm 5.3). Here is a simple version of a Dockerfile that will show the issue (using @angular/cli@latest has the same issue):

`FROM mhart/alpine-node`
`RUN npm install @angular/cli@1.1.2 -g`

When building the image:
Unable to save binary /usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux_musl-x64-57 : { Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:891:18)
    at sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor' }

I built a Docker image based off the latest Dockerfile in this repo but set the npm version to 4.2 and the issue goes away. Until the issues with npm 5 get worked out I recommend you stick with a proven version of npm.

Thank you for this great light weight node image. I have enjoyed using it so far.

**Comment by mhart** [comment]
Hi, what's the npm command you're trying to run? `npm install @1.1.2 -g`?

What module are you trying to install with that command?

**Comment by ghost** [comment]
I fixed the formatting in the first comment. I forgot to escape my '@'.

**Comment by mhart** [comment]
@kgorlick thanks – I can reproduce

I suspect it might be this: https://github.com/npm/npm/issues/17851

**Comment by ghost** [comment]
@mhart, agreed. I know this is not your issue, but figured I would give you a heads up.

Thanks again

**Comment by mhart** [comment]
No, thanks, for sure – I thought all permissions problems had been fixed by npm 5.3.0 tbh!

**Comment by mhart** [comment]
FWIW, I think the workaround here is to use `yarn`.

Try:

```Dockerfile
FROM mhart/alpine-node
RUN yarn global add @angular/cli@1.1.2
```

**Comment by ghost** [comment]
Posting this in case anyone else runs into an issue with angular@1.5.x....

Issue is back trying to get @angular/cli@1.5.x

Your yarn suggestion works like a charm.

+1 for Michael!!!
